#!/bin/bash
# Copyright 2023 EPFL
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

find hw/rtl tb -name '*.sv*' | xargs verible-verilog-format --inplace 2> /dev/zero
